/*
389. Find the Difference
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
*/


class Solution27
 {
    public char findTheDifference(String s, String t) {
       int s_sum= 0;
       int t_sum = 0;
       for(int i = 0; i<s.length() ;i++)
       {
        s_sum += s.charAt(i);
       }
       for(int i = 0;i<t.length(); i++)
       {
        t_sum += t.charAt(i);
       }
       int result = t_sum - s_sum;
      return (char) result;
    }
}